function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function inline(line) {
  let out = escapeHtml(line);
  out = out.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/_(.+?)_/g, '<em>$1</em>');
  return out;
}

// Minimal renderer for the export document: headings, bullet/checkbox
// lists and paragraphs. The markdown here is always generated by our own
// export endpoint, but user-entered text inside it is still escaped.
export function markdownToHtml(md) {
  const lines = md.split('\n');
  const html = [];
  let listOpen = false;

  const closeList = () => {
    if (listOpen) {
      html.push('</ul>');
      listOpen = false;
    }
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) {
      closeList();
      continue;
    }
    if (line.startsWith('### ')) {
      closeList();
      html.push(`<h3>${inline(line.slice(4))}</h3>`);
    } else if (line.startsWith('## ')) {
      closeList();
      html.push(`<h2>${inline(line.slice(3))}</h2>`);
    } else if (line.startsWith('# ')) {
      closeList();
      html.push(`<h1>${inline(line.slice(2))}</h1>`);
    } else if (line.startsWith('- [ ] ') || line.startsWith('- [x] ')) {
      if (!listOpen) { html.push('<ul>'); listOpen = true; }
      const done = line.startsWith('- [x] ');
      html.push(`<li style="${done ? 'text-decoration:line-through;color:#888' : ''}">${inline(line.slice(6))}</li>`);
    } else if (line.startsWith('- ')) {
      if (!listOpen) { html.push('<ul>'); listOpen = true; }
      html.push(`<li>${inline(line.slice(2))}</li>`);
    } else if (line.startsWith('_') && line.endsWith('_') && line.length > 1) {
      closeList();
      html.push(`<p><em>${inline(line.slice(1, -1))}</em></p>`);
    } else {
      closeList();
      html.push(`<p>${inline(line)}</p>`);
    }
  }
  closeList();
  return html.join('\n');
}
